//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odata_demo_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryLang
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public int LanguageID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
    }
}
