//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odata_demo_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetails
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LastContactDate { get; set; }
        public Nullable<int> LastContactedBy { get; set; }
        public string Email { get; set; }
        public bool SendBulletin { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
