//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odata_demo_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRepresentatives
    {
        public int RepresentativeID { get; set; }
        public int CustomerID { get; set; }
        public int EmployeeID { get; set; }
    }
}
