//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odata_demo_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meetings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meetings()
        {
            this.MeetingAgendas = new HashSet<MeetingAgendas>();
            this.MeetingAttendees = new HashSet<MeetingAttendees>();
            this.MeetingDecisions = new HashSet<MeetingDecisions>();
        }
    
        public int MeetingId { get; set; }
        public string MeetingName { get; set; }
        public string MeetingNumber { get; set; }
        public System.Guid MeetingGuid { get; set; }
        public int MeetingTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> OrganizerContactId { get; set; }
        public Nullable<int> ReporterContactId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual BusinessUnits BusinessUnits { get; set; }
        public virtual Contacts Contacts { get; set; }
        public virtual Contacts Contacts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingAgendas> MeetingAgendas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingAttendees> MeetingAttendees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingDecisions> MeetingDecisions { get; set; }
        public virtual MeetingLocations MeetingLocations { get; set; }
        public virtual MeetingTypes MeetingTypes { get; set; }
    }
}
