//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odata_demo_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingDecisions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingDecisions()
        {
            this.MeetingDecisionRelevant = new HashSet<MeetingDecisionRelevant>();
        }
    
        public int DecisionId { get; set; }
        public int MeetingId { get; set; }
        public int AgendaId { get; set; }
        public string Description { get; set; }
        public int DecisionNumber { get; set; }
        public Nullable<int> ResponsibleContactId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int ResolutionStatus { get; set; }
        public string Images { get; set; }
        public string Attachments { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual MeetingAgendas MeetingAgendas { get; set; }
        public virtual MeetingAgendaTypes MeetingAgendaTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingDecisionRelevant> MeetingDecisionRelevant { get; set; }
        public virtual Meetings Meetings { get; set; }
    }
}
