//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odata_demo_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingAgendas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingAgendas()
        {
            this.MeetingAgendaRelevant = new HashSet<MeetingAgendaRelevant>();
            this.MeetingDecisions = new HashSet<MeetingDecisions>();
        }
    
        public int AgendaId { get; set; }
        public int MeetingId { get; set; }
        public int AgendaNumber { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int AgendaTypeId { get; set; }
        public Nullable<int> RequestedByContactId { get; set; }
        public string Images { get; set; }
        public string Attachments { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingAgendaRelevant> MeetingAgendaRelevant { get; set; }
        public virtual MeetingAgendaTypes MeetingAgendaTypes { get; set; }
        public virtual Meetings Meetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingDecisions> MeetingDecisions { get; set; }
    }
}
