//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odata_demo_new
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Serene2_Default_v1Entities : DbContext
    {
        public Serene2_Default_v1Entities()
            : base("name=Serene2_Default_v1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessUnits> BusinessUnits { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Exceptions> Exceptions { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<MeetingAgendaRelevant> MeetingAgendaRelevant { get; set; }
        public virtual DbSet<MeetingAgendas> MeetingAgendas { get; set; }
        public virtual DbSet<MeetingAgendaTypes> MeetingAgendaTypes { get; set; }
        public virtual DbSet<MeetingAttendees> MeetingAttendees { get; set; }
        public virtual DbSet<MeetingDecisionRelevant> MeetingDecisionRelevant { get; set; }
        public virtual DbSet<MeetingDecisions> MeetingDecisions { get; set; }
        public virtual DbSet<MeetingLocations> MeetingLocations { get; set; }
        public virtual DbSet<Meetings> Meetings { get; set; }
        public virtual DbSet<MeetingTypes> MeetingTypes { get; set; }
        public virtual DbSet<RolePermissions> RolePermissions { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserPermissions> UserPermissions { get; set; }
        public virtual DbSet<UserPreferences> UserPreferences { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VersionInfo> VersionInfo { get; set; }
    }
}
