//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odata_demo_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public long NoteID { get; set; }
        public string EntityType { get; set; }
        public long EntityID { get; set; }
        public string Text { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertDate { get; set; }
    }
}
